spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: user_dev
    password: 123456
    url: jdbc:h2:mem:pix_wallet_db;MODE=POSTGRESQL;DATABASE_TO_LOWER=TRUE
  h2:
    console:
      enabled: true
      path: /h2

pix:
  wallet:
    security:
      enabled: false